##############
### local
##############
jwt:
  secret-key: 6e045a07fe01a595836901e3fea138730156ae02b792586df0e06ba62a91a8b1fdc091b49e4c0fe5e902f643b992294c93a53f1e059fb01623d90218977d1e5d

server:
  port: 8080
spring:
  h2:
    # h2 DB
    console:
      enabled: true
      path: /h2-console
  # Database Platform
  sql:
    init:
      platform: h2
      mode: embedded
#r2dbc
  r2dbc:
    url: r2dbc:h2:mem:///./testdb
    usename: sa
    password:

# spring boot - actuator expose
management:
  endpoints:
    health:
      show-details: always
      enabled: true
    loggers:
      enabled: true  
    prometheus:
      enabled: true
    web:
      exposure:
        include: health,prometheus,loggers,metrics,caches,beans
  endpoint:
    health:
      probes:
        enabled: true


# app
app-info:
  node-ip: "192.168.0.1"
  pod-ip: "192.168.0.1"
  pod-name: "test"
  app-name: "edu11"

springdoc:
  show-actuator: true  # actuator swagger 노출
  swagger-ui:
    groups-order: DESC
    #operations-sorter: alpha
    #tags-sorter: alpha
    disable-swagger-default-url: true
    #doc-expansion: none

logging:
  level:
    com.kt.edu: trace
    org:
      springframework:
        r2dbc:
          core:
            DefaultDatabaseClient: debug